spring.application.name=myapp
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.ai.openai.api-key=${OPENAI_API_KEY}

server.error.include-message=always
logging.level.com.skala.lab0.myapp=INFO

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.security.user.name=admin
spring.security.user.password=${LAB3_ADMIN_PASSWORD:admin}
spring.security.user.roles=ADMIN

lab2.rag.chunk-size=400
lab2.rag.search.min-score=0.29

management.endpoints.web.exposure.include=health,info, metrics
